-- Questions (validated on 2026-10-02, page « Questionnaires par niveau »).
-- The bank: 34 questions, each written once, numbered here as on the page.
-- The lists: ordered selections of the bank, attached to sectors and services;
-- the lists of the sector, type and service add up on screen 6. A question in
-- several lists is the same question, so its answers compare across sectors.
-- Nothing attached: Sécurité (waiting for the operating body), Transport (no
-- question fits every means of transport), type Aéroport (later), service État
-- civil (adds nothing to « Services à dossier »). GENERIC also serves the
-- establishments whose sector is unknown (in src/domain).
-- Generated from one description to avoid copying mistakes.


INSERT INTO question (code, type) VALUES
  ('OVERALL_SATISFACTION', 'scale_5'),
  ('REPORTED', 'single_choice'),
  ('REPORT_WHY', 'single_choice'),
  ('GOAL_ACHIEVED', 'yes_partial_no'),
  ('WAIT_TIME', 'single_choice'),
  ('VISITS_COUNT', 'single_choice'),
  ('DOCUMENTS_KNOWN', 'yes_partial_no'),
  ('RECEIPT_GIVEN', 'single_choice'),
  ('FEES_EXPLAINED', 'yes_partial_no'),
  ('PAYMENT_AS_WISHED', 'single_choice'),
  ('PATIENT', 'single_choice'),
  ('CARE_RECEIVED', 'yes_partial_no'),
  ('PRESCRIPTION_AVAILABLE', 'single_choice'),
  ('RESPONDENT', 'single_choice'),
  ('CLASSES_HELD', 'single_choice'),
  ('CLASS_SIZE', 'single_choice'),
  ('FACILITIES', 'yes_partial_no'),
  ('UTILITY_SUBJECT', 'single_choice'),
  ('CUTS_COUNT', 'single_choice'),
  ('DAYS_WITHOUT_WATER', 'single_choice'),
  ('CUT_NOTICE', 'single_choice'),
  ('PREPAID_METER', 'single_choice'),
  ('TELECOM_SUBJECT', 'single_choice'),
  ('NETWORK_LOSS', 'single_choice'),
  ('STOP_WAIT', 'single_choice'),
  ('CROWDED', 'single_choice'),
  ('TICKET_GIVEN', 'single_choice'),
  ('DEPARTURE_ON_TIME', 'single_choice'),
  ('BOARDING', 'yes_partial_no'),
  ('SEAT_AS_BOOKED', 'single_choice'),
  ('SAFETY_BRIEFING', 'single_choice'),
  ('FAIR_PRICE', 'single_choice'),
  ('RECEIPT_OR_INVOICE', 'single_choice'),
  ('RECOMMEND', 'single_choice');

INSERT INTO question_translation (question_id, language, label)
SELECT q.id, 'fr', v.label
FROM (VALUES
  ('OVERALL_SATISFACTION', 'Êtes-vous satisfait(e) du service reçu ?'),
  ('REPORTED', 'Avez-vous signalé cette situation à l''établissement (accueil, service client, direction…) ?'),
  ('REPORT_WHY', 'Pourquoi ?'),
  ('GOAL_ACHIEVED', 'Avez-vous obtenu ce que vous étiez venu(e) chercher ?'),
  ('WAIT_TIME', 'Combien de temps avez-vous attendu avant d''être reçu(e) ?'),
  ('VISITS_COUNT', 'Combien de fois êtes-vous venu(e) pour cette démarche ?'),
  ('DOCUMENTS_KNOWN', 'Saviez-vous à l''avance quels papiers apporter ?'),
  ('RECEIPT_GIVEN', 'Vous a-t-on donné un reçu pour ce que vous avez payé ?'),
  ('FEES_EXPLAINED', 'Les frais vous ont-ils été expliqués clairement ?'),
  ('PAYMENT_AS_WISHED', 'Avez-vous pu payer comme vous le souhaitiez (espèces, paiement mobile…) ?'),
  ('PATIENT', 'Pour qui êtes-vous venu(e) ?'),
  ('CARE_RECEIVED', 'Avez-vous reçu les soins pour lesquels vous étiez venu(e) ?'),
  ('PRESCRIPTION_AVAILABLE', 'Les médicaments ou examens prescrits étaient-ils disponibles sur place ?'),
  ('RESPONDENT', 'Vous êtes :'),
  ('CLASSES_HELD', 'Les cours ont-ils eu lieu comme prévu ces dernières semaines ?'),
  ('CLASS_SIZE', 'Combien d''élèves y a-t-il dans la classe ?'),
  ('FACILITIES', 'Les toilettes et l''eau fonctionnent-elles ?'),
  ('UTILITY_SUBJECT', 'Votre avis porte surtout sur :'),
  ('CUTS_COUNT', 'Combien de coupures avez-vous eues ce mois-ci ?'),
  ('DAYS_WITHOUT_WATER', 'Combien de jours sans eau ce mois-ci ?'),
  ('CUT_NOTICE', 'Avez-vous été prévenu(e) avant les coupures ?'),
  ('PREPAID_METER', 'Avez-vous un compteur Woyofal (prépayé) ?'),
  ('TELECOM_SUBJECT', 'Votre avis porte surtout sur :'),
  ('NETWORK_LOSS', 'À quelle fréquence perdez-vous le réseau ?'),
  ('STOP_WAIT', 'Combien de temps avez-vous attendu à l''arrêt ou en gare ?'),
  ('CROWDED', 'Le véhicule était-il bondé ?'),
  ('TICKET_GIVEN', 'Vous a-t-on donné un ticket pour votre trajet ?'),
  ('DEPARTURE_ON_TIME', 'Le bateau est-il parti à l''heure prévue ?'),
  ('BOARDING', 'L''embarquement s''est-il bien passé ?'),
  ('SEAT_AS_BOOKED', 'Aviez-vous une place correspondant à votre billet (siège, couchette, cabine) ?'),
  ('SAFETY_BRIEFING', 'Les consignes de sécurité (gilets, exercices) ont-elles été présentées ?'),
  ('FAIR_PRICE', 'Le prix vous a-t-il semblé juste ?'),
  ('RECEIPT_OR_INVOICE', 'Vous a-t-on donné un reçu ou une facture ?'),
  ('RECOMMEND', 'Recommanderiez-vous cet établissement à un proche ?')
) AS v (code, label)
JOIN question q ON q.code = v.code;

INSERT INTO answer_option (question_id, code, value, position)
SELECT q.id, v.option, v.value, v.position
FROM (VALUES
  ('OVERALL_SATISFACTION', 'VERY_SATISFIED', 5, 1),
  ('OVERALL_SATISFACTION', 'SATISFIED', 4, 2),
  ('OVERALL_SATISFACTION', 'NEUTRAL', 3, 3),
  ('OVERALL_SATISFACTION', 'DISSATISFIED', 2, 4),
  ('OVERALL_SATISFACTION', 'VERY_DISSATISFIED', 1, 5),
  ('REPORTED', 'YES_ANSWERED', NULL, 1),
  ('REPORTED', 'YES_NO_ANSWER', NULL, 2),
  ('REPORTED', 'COULD_NOT_REACH', NULL, 3),
  ('REPORTED', 'NO', NULL, 4),
  ('REPORT_WHY', 'DID_NOT_KNOW_WHO', NULL, 1),
  ('REPORT_WHY', 'POINTLESS', NULL, 2),
  ('REPORT_WHY', 'OTHER', NULL, 3),
  ('GOAL_ACHIEVED', 'YES', 3, 1),
  ('GOAL_ACHIEVED', 'PARTLY', 2, 2),
  ('GOAL_ACHIEVED', 'NO', 1, 3),
  ('WAIT_TIME', 'UNDER_30_MIN', 1, 1),
  ('WAIT_TIME', '30_MIN_TO_1_H', 2, 2),
  ('WAIT_TIME', '1_TO_2_H', 3, 3),
  ('WAIT_TIME', '2_TO_4_H', 4, 4),
  ('WAIT_TIME', 'OVER_4_H', 5, 5),
  ('VISITS_COUNT', 'ONCE', 1, 1),
  ('VISITS_COUNT', 'TWICE', 2, 2),
  ('VISITS_COUNT', 'THREE_OR_MORE', 3, 3),
  ('DOCUMENTS_KNOWN', 'YES', 3, 1),
  ('DOCUMENTS_KNOWN', 'PARTLY', 2, 2),
  ('DOCUMENTS_KNOWN', 'NO', 1, 3),
  ('RECEIPT_GIVEN', 'FOR_ALL', 3, 1),
  ('RECEIPT_GIVEN', 'FOR_SOME', 2, 2),
  ('RECEIPT_GIVEN', 'NO', 1, 3),
  ('RECEIPT_GIVEN', 'NOTHING_PAID', NULL, 4),
  ('FEES_EXPLAINED', 'YES', 3, 1),
  ('FEES_EXPLAINED', 'PARTLY', 2, 2),
  ('FEES_EXPLAINED', 'NO', 1, 3),
  ('PAYMENT_AS_WISHED', 'YES', 2, 1),
  ('PAYMENT_AS_WISHED', 'NO', 1, 2),
  ('PATIENT', 'SELF', NULL, 1),
  ('PATIENT', 'CHILD', NULL, 2),
  ('PATIENT', 'OTHER_RELATIVE', NULL, 3),
  ('CARE_RECEIVED', 'YES', 3, 1),
  ('CARE_RECEIVED', 'PARTLY', 2, 2),
  ('CARE_RECEIVED', 'NO', 1, 3),
  ('PRESCRIPTION_AVAILABLE', 'ALL', 3, 1),
  ('PRESCRIPTION_AVAILABLE', 'SOME', 2, 2),
  ('PRESCRIPTION_AVAILABLE', 'NONE', 1, 3),
  ('PRESCRIPTION_AVAILABLE', 'NOTHING_PRESCRIBED', NULL, 4),
  ('RESPONDENT', 'STUDENT', NULL, 1),
  ('RESPONDENT', 'PARENT', NULL, 2),
  ('RESPONDENT', 'OTHER', NULL, 3),
  ('CLASSES_HELD', 'YES', 3, 1),
  ('CLASSES_HELD', 'SOME_ABSENCES', 2, 2),
  ('CLASSES_HELD', 'MANY_ABSENCES', 1, 3),
  ('CLASS_SIZE', 'UNDER_40', 1, 1),
  ('CLASS_SIZE', '40_TO_60', 2, 2),
  ('CLASS_SIZE', 'OVER_60', 3, 3),
  ('CLASS_SIZE', 'DONT_KNOW', NULL, 4),
  ('FACILITIES', 'YES', 3, 1),
  ('FACILITIES', 'PARTLY', 2, 2),
  ('FACILITIES', 'NO', 1, 3),
  ('UTILITY_SUBJECT', 'CUT', NULL, 1),
  ('UTILITY_SUBJECT', 'BILL', NULL, 2),
  ('UTILITY_SUBJECT', 'CONNECTION', NULL, 3),
  ('UTILITY_SUBJECT', 'OTHER', NULL, 4),
  ('CUTS_COUNT', 'NONE', 0, 1),
  ('CUTS_COUNT', '1_TO_3', 1, 2),
  ('CUTS_COUNT', '4_TO_10', 2, 3),
  ('CUTS_COUNT', 'OVER_10', 3, 4),
  ('DAYS_WITHOUT_WATER', 'NONE', 0, 1),
  ('DAYS_WITHOUT_WATER', '1_TO_3', 1, 2),
  ('DAYS_WITHOUT_WATER', '4_TO_10', 2, 3),
  ('DAYS_WITHOUT_WATER', 'OVER_10', 3, 4),
  ('CUT_NOTICE', 'YES', 3, 1),
  ('CUT_NOTICE', 'SOMETIMES', 2, 2),
  ('CUT_NOTICE', 'NO', 1, 3),
  ('PREPAID_METER', 'YES', NULL, 1),
  ('PREPAID_METER', 'NO', NULL, 2),
  ('TELECOM_SUBJECT', 'CALLS_SMS', NULL, 1),
  ('TELECOM_SUBJECT', 'MOBILE_INTERNET', NULL, 2),
  ('TELECOM_SUBJECT', 'MOBILE_MONEY', NULL, 3),
  ('TELECOM_SUBJECT', 'HOME_INTERNET', NULL, 4),
  ('TELECOM_SUBJECT', 'BILLING', NULL, 5),
  ('NETWORK_LOSS', 'NEVER', 4, 1),
  ('NETWORK_LOSS', 'SOMETIMES', 3, 2),
  ('NETWORK_LOSS', 'OFTEN', 2, 3),
  ('NETWORK_LOSS', 'DAILY', 1, 4),
  ('STOP_WAIT', 'UNDER_10_MIN', 1, 1),
  ('STOP_WAIT', '10_TO_30_MIN', 2, 2),
  ('STOP_WAIT', '30_MIN_TO_1_H', 3, 3),
  ('STOP_WAIT', 'OVER_1_H', 4, 4),
  ('CROWDED', 'NO', 3, 1),
  ('CROWDED', 'A_LITTLE', 2, 2),
  ('CROWDED', 'VERY', 1, 3),
  ('TICKET_GIVEN', 'YES', 2, 1),
  ('TICKET_GIVEN', 'NO', 1, 2),
  ('TICKET_GIVEN', 'NOT_EXPECTED', NULL, 3),
  ('DEPARTURE_ON_TIME', 'ON_TIME', 4, 1),
  ('DEPARTURE_ON_TIME', 'UNDER_1_H_LATE', 3, 2),
  ('DEPARTURE_ON_TIME', 'OVER_1_H_LATE', 2, 3),
  ('DEPARTURE_ON_TIME', 'CANCELLED', 1, 4),
  ('BOARDING', 'YES', 3, 1),
  ('BOARDING', 'PARTLY', 2, 2),
  ('BOARDING', 'NO', 1, 3),
  ('SEAT_AS_BOOKED', 'YES', 2, 1),
  ('SEAT_AS_BOOKED', 'NO', 1, 2),
  ('SAFETY_BRIEFING', 'YES', 2, 1),
  ('SAFETY_BRIEFING', 'NO', 1, 2),
  ('SAFETY_BRIEFING', 'DONT_KNOW', NULL, 3),
  ('FAIR_PRICE', 'YES', 3, 1),
  ('FAIR_PRICE', 'ROUGHLY', 2, 2),
  ('FAIR_PRICE', 'NO', 1, 3),
  ('FAIR_PRICE', 'NOTHING_PAID', NULL, 4),
  ('RECEIPT_OR_INVOICE', 'YES', 2, 1),
  ('RECEIPT_OR_INVOICE', 'NO', 1, 2),
  ('RECEIPT_OR_INVOICE', 'NOTHING_PAID', NULL, 3),
  ('RECOMMEND', 'YES', 3, 1),
  ('RECOMMEND', 'MAYBE', 2, 2),
  ('RECOMMEND', 'NO', 1, 3)
) AS v (question, option, value, position)
JOIN question q ON q.code = v.question;

INSERT INTO answer_option_translation (answer_option_id, language, label, follow_up_prompt)
SELECT ao.id, 'fr', v.label, v.prompt
FROM (VALUES
  ('OVERALL_SATISFACTION', 'VERY_SATISFIED', 'Très satisfait(e)', 'Qu''est-ce qui vous a plu ?'),
  ('OVERALL_SATISFACTION', 'SATISFIED', 'Satisfait(e)', 'Qu''est-ce qui vous a plu ?'),
  ('OVERALL_SATISFACTION', 'NEUTRAL', 'Moyennement satisfait(e)', 'Qu''est-ce qui aurait pu être mieux ?'),
  ('OVERALL_SATISFACTION', 'DISSATISFIED', 'Peu satisfait(e)', 'Que s''est-il passé ?'),
  ('OVERALL_SATISFACTION', 'VERY_DISSATISFIED', 'Pas du tout satisfait(e)', 'Que s''est-il passé ?'),
  ('REPORTED', 'YES_ANSWERED', 'Oui, et on m''a répondu', NULL),
  ('REPORTED', 'YES_NO_ANSWER', 'Oui, mais sans réponse', NULL),
  ('REPORTED', 'COULD_NOT_REACH', 'J''ai essayé, sans réussir à les joindre', NULL),
  ('REPORTED', 'NO', 'Non', NULL),
  ('REPORT_WHY', 'DID_NOT_KNOW_WHO', 'Je ne savais pas à qui m''adresser', NULL),
  ('REPORT_WHY', 'POINTLESS', 'Je pensais que ça ne servirait à rien', NULL),
  ('REPORT_WHY', 'OTHER', 'Autre raison', NULL),
  ('GOAL_ACHIEVED', 'YES', 'Oui', NULL),
  ('GOAL_ACHIEVED', 'PARTLY', 'En partie', NULL),
  ('GOAL_ACHIEVED', 'NO', 'Non', NULL),
  ('WAIT_TIME', 'UNDER_30_MIN', 'Moins de 30 minutes', NULL),
  ('WAIT_TIME', '30_MIN_TO_1_H', '30 minutes à 1 heure', NULL),
  ('WAIT_TIME', '1_TO_2_H', '1 à 2 heures', NULL),
  ('WAIT_TIME', '2_TO_4_H', '2 à 4 heures', NULL),
  ('WAIT_TIME', 'OVER_4_H', 'Plus de 4 heures', NULL),
  ('VISITS_COUNT', 'ONCE', '1 fois', NULL),
  ('VISITS_COUNT', 'TWICE', '2 fois', NULL),
  ('VISITS_COUNT', 'THREE_OR_MORE', '3 fois ou plus', NULL),
  ('DOCUMENTS_KNOWN', 'YES', 'Oui', NULL),
  ('DOCUMENTS_KNOWN', 'PARTLY', 'En partie', NULL),
  ('DOCUMENTS_KNOWN', 'NO', 'Non', NULL),
  ('RECEIPT_GIVEN', 'FOR_ALL', 'Oui, pour tout', NULL),
  ('RECEIPT_GIVEN', 'FOR_SOME', 'Pour une partie', NULL),
  ('RECEIPT_GIVEN', 'NO', 'Non', NULL),
  ('RECEIPT_GIVEN', 'NOTHING_PAID', 'Je n''ai rien payé', NULL),
  ('FEES_EXPLAINED', 'YES', 'Oui', NULL),
  ('FEES_EXPLAINED', 'PARTLY', 'En partie', NULL),
  ('FEES_EXPLAINED', 'NO', 'Non', NULL),
  ('PAYMENT_AS_WISHED', 'YES', 'Oui', NULL),
  ('PAYMENT_AS_WISHED', 'NO', 'Non', NULL),
  ('PATIENT', 'SELF', 'Pour moi', NULL),
  ('PATIENT', 'CHILD', 'Pour mon enfant', NULL),
  ('PATIENT', 'OTHER_RELATIVE', 'Pour un autre proche', NULL),
  ('CARE_RECEIVED', 'YES', 'Oui', NULL),
  ('CARE_RECEIVED', 'PARTLY', 'En partie', NULL),
  ('CARE_RECEIVED', 'NO', 'Non', NULL),
  ('PRESCRIPTION_AVAILABLE', 'ALL', 'Oui, tous', NULL),
  ('PRESCRIPTION_AVAILABLE', 'SOME', 'Une partie', NULL),
  ('PRESCRIPTION_AVAILABLE', 'NONE', 'Non, aucun', NULL),
  ('PRESCRIPTION_AVAILABLE', 'NOTHING_PRESCRIBED', 'Rien n''a été prescrit', NULL),
  ('RESPONDENT', 'STUDENT', 'Élève ou étudiant(e)', NULL),
  ('RESPONDENT', 'PARENT', 'Parent', NULL),
  ('RESPONDENT', 'OTHER', 'Autre', NULL),
  ('CLASSES_HELD', 'YES', 'Oui', NULL),
  ('CLASSES_HELD', 'SOME_ABSENCES', 'Quelques absences', NULL),
  ('CLASSES_HELD', 'MANY_ABSENCES', 'Beaucoup d''absences', NULL),
  ('CLASS_SIZE', 'UNDER_40', 'Moins de 40', NULL),
  ('CLASS_SIZE', '40_TO_60', '40 à 60', NULL),
  ('CLASS_SIZE', 'OVER_60', 'Plus de 60', NULL),
  ('CLASS_SIZE', 'DONT_KNOW', 'Je ne sais pas', NULL),
  ('FACILITIES', 'YES', 'Oui', NULL),
  ('FACILITIES', 'PARTLY', 'En partie', NULL),
  ('FACILITIES', 'NO', 'Non', NULL),
  ('UTILITY_SUBJECT', 'CUT', 'Une coupure', NULL),
  ('UTILITY_SUBJECT', 'BILL', 'Une facture', NULL),
  ('UTILITY_SUBJECT', 'CONNECTION', 'Un branchement ou un compteur', NULL),
  ('UTILITY_SUBJECT', 'OTHER', 'Autre chose', NULL),
  ('CUTS_COUNT', 'NONE', 'Aucune', NULL),
  ('CUTS_COUNT', '1_TO_3', '1 à 3', NULL),
  ('CUTS_COUNT', '4_TO_10', '4 à 10', NULL),
  ('CUTS_COUNT', 'OVER_10', 'Plus de 10', NULL),
  ('DAYS_WITHOUT_WATER', 'NONE', 'Aucun', NULL),
  ('DAYS_WITHOUT_WATER', '1_TO_3', '1 à 3', NULL),
  ('DAYS_WITHOUT_WATER', '4_TO_10', '4 à 10', NULL),
  ('DAYS_WITHOUT_WATER', 'OVER_10', 'Plus de 10', NULL),
  ('CUT_NOTICE', 'YES', 'Oui', NULL),
  ('CUT_NOTICE', 'SOMETIMES', 'Parfois', NULL),
  ('CUT_NOTICE', 'NO', 'Non', NULL),
  ('PREPAID_METER', 'YES', 'Oui', NULL),
  ('PREPAID_METER', 'NO', 'Non', NULL),
  ('TELECOM_SUBJECT', 'CALLS_SMS', 'Appels et SMS', NULL),
  ('TELECOM_SUBJECT', 'MOBILE_INTERNET', 'Internet mobile', NULL),
  ('TELECOM_SUBJECT', 'MOBILE_MONEY', 'Mobile money', NULL),
  ('TELECOM_SUBJECT', 'HOME_INTERNET', 'Internet à la maison', NULL),
  ('TELECOM_SUBJECT', 'BILLING', 'Facture ou crédit', NULL),
  ('NETWORK_LOSS', 'NEVER', 'Jamais', NULL),
  ('NETWORK_LOSS', 'SOMETIMES', 'Parfois', NULL),
  ('NETWORK_LOSS', 'OFTEN', 'Souvent', NULL),
  ('NETWORK_LOSS', 'DAILY', 'Tous les jours', NULL),
  ('STOP_WAIT', 'UNDER_10_MIN', 'Moins de 10 minutes', NULL),
  ('STOP_WAIT', '10_TO_30_MIN', '10 à 30 minutes', NULL),
  ('STOP_WAIT', '30_MIN_TO_1_H', '30 minutes à 1 heure', NULL),
  ('STOP_WAIT', 'OVER_1_H', 'Plus d''1 heure', NULL),
  ('CROWDED', 'NO', 'Non', NULL),
  ('CROWDED', 'A_LITTLE', 'Un peu', NULL),
  ('CROWDED', 'VERY', 'Beaucoup', NULL),
  ('TICKET_GIVEN', 'YES', 'Oui', NULL),
  ('TICKET_GIVEN', 'NO', 'Non', NULL),
  ('TICKET_GIVEN', 'NOT_EXPECTED', 'Ce n''était pas prévu', NULL),
  ('DEPARTURE_ON_TIME', 'ON_TIME', 'À l''heure', NULL),
  ('DEPARTURE_ON_TIME', 'UNDER_1_H_LATE', 'Moins d''1 heure de retard', NULL),
  ('DEPARTURE_ON_TIME', 'OVER_1_H_LATE', 'Plus d''1 heure de retard', NULL),
  ('DEPARTURE_ON_TIME', 'CANCELLED', 'Départ annulé ou reporté', NULL),
  ('BOARDING', 'YES', 'Oui', NULL),
  ('BOARDING', 'PARTLY', 'En partie', NULL),
  ('BOARDING', 'NO', 'Non', NULL),
  ('SEAT_AS_BOOKED', 'YES', 'Oui', NULL),
  ('SEAT_AS_BOOKED', 'NO', 'Non', NULL),
  ('SAFETY_BRIEFING', 'YES', 'Oui', NULL),
  ('SAFETY_BRIEFING', 'NO', 'Non', NULL),
  ('SAFETY_BRIEFING', 'DONT_KNOW', 'Je ne sais pas', NULL),
  ('FAIR_PRICE', 'YES', 'Oui', NULL),
  ('FAIR_PRICE', 'ROUGHLY', 'À peu près', NULL),
  ('FAIR_PRICE', 'NO', 'Non', NULL),
  ('FAIR_PRICE', 'NOTHING_PAID', 'Je n''ai rien payé', NULL),
  ('RECEIPT_OR_INVOICE', 'YES', 'Oui', NULL),
  ('RECEIPT_OR_INVOICE', 'NO', 'Non', NULL),
  ('RECEIPT_OR_INVOICE', 'NOTHING_PAID', 'Je n''ai rien payé', NULL),
  ('RECOMMEND', 'YES', 'Oui', NULL),
  ('RECOMMEND', 'MAYBE', 'Peut-être', NULL),
  ('RECOMMEND', 'NO', 'Non', NULL)
) AS v (question, option, label, prompt)
JOIN question q ON q.code = v.question
JOIN answer_option ao ON ao.question_id = q.id AND ao.code = v.option;

INSERT INTO question_set (code) VALUES
  ('ESSENTIAL'),
  ('COMMON'),
  ('FILE_SERVICES'),
  ('HEALTH'),
  ('BANKING_INSURANCE'),
  ('EDUCATION'),
  ('ELECTRICITY'),
  ('WATER'),
  ('TELECOM'),
  ('LAND_TRIP'),
  ('BOAT_CROSSING'),
  ('TICKET_PURCHASE'),
  ('GENERIC');

INSERT INTO question_set_item (question_set_id, question_id, position)
SELECT qs.id, q.id, v.position
FROM (VALUES
  ('ESSENTIAL', 'OVERALL_SATISFACTION', 1),
  ('COMMON', 'REPORTED', 1),
  ('COMMON', 'REPORT_WHY', 2),
  ('FILE_SERVICES', 'GOAL_ACHIEVED', 1),
  ('FILE_SERVICES', 'VISITS_COUNT', 2),
  ('FILE_SERVICES', 'WAIT_TIME', 3),
  ('FILE_SERVICES', 'DOCUMENTS_KNOWN', 4),
  ('FILE_SERVICES', 'RECEIPT_GIVEN', 5),
  ('HEALTH', 'PATIENT', 1),
  ('HEALTH', 'CARE_RECEIVED', 2),
  ('HEALTH', 'WAIT_TIME', 3),
  ('HEALTH', 'PRESCRIPTION_AVAILABLE', 4),
  ('HEALTH', 'RECEIPT_GIVEN', 5),
  ('BANKING_INSURANCE', 'GOAL_ACHIEVED', 1),
  ('BANKING_INSURANCE', 'WAIT_TIME', 2),
  ('BANKING_INSURANCE', 'FEES_EXPLAINED', 3),
  ('EDUCATION', 'RESPONDENT', 1),
  ('EDUCATION', 'CLASSES_HELD', 2),
  ('EDUCATION', 'CLASS_SIZE', 3),
  ('EDUCATION', 'FACILITIES', 4),
  ('EDUCATION', 'RECEIPT_GIVEN', 5),
  ('ELECTRICITY', 'UTILITY_SUBJECT', 1),
  ('ELECTRICITY', 'CUTS_COUNT', 2),
  ('ELECTRICITY', 'CUT_NOTICE', 3),
  ('ELECTRICITY', 'PREPAID_METER', 4),
  ('WATER', 'UTILITY_SUBJECT', 1),
  ('WATER', 'DAYS_WITHOUT_WATER', 2),
  ('WATER', 'CUT_NOTICE', 3),
  ('TELECOM', 'TELECOM_SUBJECT', 1),
  ('TELECOM', 'NETWORK_LOSS', 2),
  ('LAND_TRIP', 'STOP_WAIT', 1),
  ('LAND_TRIP', 'CROWDED', 2),
  ('LAND_TRIP', 'TICKET_GIVEN', 3),
  ('BOAT_CROSSING', 'DEPARTURE_ON_TIME', 1),
  ('BOAT_CROSSING', 'BOARDING', 2),
  ('BOAT_CROSSING', 'SEAT_AS_BOOKED', 3),
  ('BOAT_CROSSING', 'SAFETY_BRIEFING', 4),
  ('TICKET_PURCHASE', 'GOAL_ACHIEVED', 1),
  ('TICKET_PURCHASE', 'WAIT_TIME', 2),
  ('TICKET_PURCHASE', 'PAYMENT_AS_WISHED', 3),
  ('GENERIC', 'FAIR_PRICE', 1),
  ('GENERIC', 'RECEIPT_OR_INVOICE', 2),
  ('GENERIC', 'RECOMMEND', 3)
) AS v (question_set, question, position)
JOIN question_set qs ON qs.code = v.question_set
JOIN question q ON q.code = v.question;

-- In COMMON: « Avez-vous signalé… ? » only when not satisfied, « Pourquoi ? »
-- only after « Non ». In ELECTRICITY and WATER: « Prévenu(e) ? » only after cuts.
INSERT INTO question_condition (question_set_id, question_id, depends_on_question_id, option_id)
SELECT qs.id, q.id, dq.id, ao.id
FROM (VALUES
  ('COMMON', 'REPORTED', 'OVERALL_SATISFACTION', 'DISSATISFIED'),
  ('COMMON', 'REPORTED', 'OVERALL_SATISFACTION', 'VERY_DISSATISFIED'),
  ('COMMON', 'REPORT_WHY', 'REPORTED', 'NO'),
  ('ELECTRICITY', 'CUT_NOTICE', 'CUTS_COUNT', '1_TO_3'),
  ('ELECTRICITY', 'CUT_NOTICE', 'CUTS_COUNT', '4_TO_10'),
  ('ELECTRICITY', 'CUT_NOTICE', 'CUTS_COUNT', 'OVER_10'),
  ('WATER', 'CUT_NOTICE', 'DAYS_WITHOUT_WATER', '1_TO_3'),
  ('WATER', 'CUT_NOTICE', 'DAYS_WITHOUT_WATER', '4_TO_10'),
  ('WATER', 'CUT_NOTICE', 'DAYS_WITHOUT_WATER', 'OVER_10')
) AS v (question_set, question, depends_on, option)
JOIN question_set qs ON qs.code = v.question_set
JOIN question q ON q.code = v.question
JOIN question dq ON dq.code = v.depends_on
JOIN answer_option ao ON ao.question_id = dq.id AND ao.code = v.option;

UPDATE sector s
SET question_set_id = qs.id
FROM (VALUES
  ('ADMINISTRATION', 'FILE_SERVICES'),
  ('TAX', 'FILE_SERVICES'),
  ('JUSTICE', 'FILE_SERVICES'),
  ('SOCIAL', 'FILE_SERVICES'),
  ('HEALTH', 'HEALTH'),
  ('BANKING_INSURANCE', 'BANKING_INSURANCE'),
  ('EDUCATION', 'EDUCATION'),
  ('ELECTRICITY', 'ELECTRICITY'),
  ('WATER', 'WATER'),
  ('TELECOM', 'TELECOM'),
  ('RETAIL', 'GENERIC'),
  ('CULTURE', 'GENERIC'),
  ('HOSPITALITY', 'GENERIC'),
  ('REAL_ESTATE', 'GENERIC'),
  ('FOOD_SERVICE', 'GENERIC'),
  ('SPORT', 'GENERIC'),
  ('TOURISM', 'GENERIC')
) AS v (sector, question_set)
JOIN question_set qs ON qs.code = v.question_set
WHERE s.code = v.sector;

UPDATE service s
SET question_set_id = qs.id
FROM (VALUES
  ('LAND_TRIP', 'LAND_TRIP'),
  ('BOAT_CROSSING', 'BOAT_CROSSING'),
  ('TICKET_PURCHASE', 'TICKET_PURCHASE')
) AS v (service, question_set)
JOIN question_set qs ON qs.code = v.question_set
WHERE s.code = v.service;
