import { upsertFeedback } from "@/src/domain/feedback";
import { readJson, respond } from "../../_lib/respond";

/** PUT /webapi/feedbacks/{id}: id is a UUID generated by the phone, so retries are safe. */
export async function PUT(request: Request, ctx: RouteContext<"/webapi/feedbacks/[id]">) {
  const { id } = await ctx.params;
  return respond(async () => upsertFeedback(id, await readJson(request)));
}
